name : joyconnWotchDog                 #服务名称
displayName : joyconnWotchDog          #服务显示名称
description : joyconn服务活动监测       #服务描述
services : 
  - checkName : 'powerfinalstation'  #监测项名称
    checkType : 1  #监测类型 1url(get) 2url(post)
    checkAddr : 'http://127.0.0.1:8012/js/joyconn/utils.js'  #监测地址
    errOp : 'net stop power-finals-tation & net start power-finals-tation'  #监测失败时需要执行的动作(cmd/shell)
    errOpSpan : 1800  #监测失败时执行动作的最小时间间隔 单位秒
    checkCorn : 0 0/1 * * * ?  #监测周期
  